name: lntree
base: core18
type: app
version: 0.1.1
summary: A tool to symlink the leaves of a directory tree to a certain path
description: |
  ```
  lntree SRC DST [OPTIONS]
  ```

  where 
  * SRC can be a file, a dir or a group of them (metacharacters) where dst will point to
  * DST is the path to a folder that is the root of the tree whose leaves will be linked to src

  optional
  --clear unlink destinations instead of creating them

grade: stable
confinement: strict

parts:
  lntree:
    plugin: python
    python-version: python3
    source: .

apps:
  lntree:
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
    command: bin/lntree
    plugs: [home]
